let aboutApiData = [
    {
      Biling_location: "Riyadh Kingdom of Saudi Arabia",
      Entity_Name: "Lucas Film Private Ltd",
      Entity_Code: "LUCF01",
      MSLA: "2 Jan 2020 - 5 June 2028 ",
      file_sharing: "Mail",
      address: {
        line1: "LINE1",
        line2: "LINE2",
        city_country: "City contry",
        ZIP_Code: "ZIP Code"
      },
      PO_Number: "Required",
      Company_Registration: "HJGUDFBSF5130SF",
      company_regis_validity: "5 June 2030",
      Duration_file: "90 days",
      TAX: "HUFDHSF5315SDF",
      TRN: "5 JUNE 2030",
      Currency: "UK Dollar (S)",
      VAT: "3%",
      WHT: "8%",
    },
    {
      Biling_location: "Riyadh Kingdom of Saudi Arabia",
      Entity_Name: "Lucas Film Private Ltd",
      Entity_Code: "LUCF01",
      MSLA: "3 June 2022 - 5 June 2030",
      file_sharing: "External",
      address: {
        line1: "LINE1",
        line2: "LINE2",
        city_country: "City contry",
      },
      PO_Number: "Required",
      Company_Registration: "HJGUDFBSF5130SF",
      company_regis_validity: "5 June 2030",
      Duration_file: "90 days",
      TAX: "HUFDHSF5315SDF",
      TRN: "5 JUNE 2025",
      Currency: "US Dollar (S)",
      VAT: "5%",
      WHT: "5%",
    },
    {
      Biling_location: "Riyadh Kingdom of Saudi Arabia",
      Entity_Name: "Lucas Film Private Ltd",
      Entity_Code: "LUCF02",
      MSLA: "10 may 2022 - 5 sept 2035",
      file_sharing: "Draft",
      address: {
        line1: "LINE3",
        line2: "LINE4",
        city_country: "Bangluru India",
      },
      PO_Number: "Required",
      Company_Registration: "HJDSF6555DS",
      company_regis_validity: "5 June 2030",
      Duration_file: "90 days",
      TAX: "HUFDHSF5315SDF",
      TRN: "5 JUNE 2025",
      Currency: "US Dollar (S)",
      VAT: "15%",
      WHT: "15%",
    },
  ];
  export default aboutApiData;